/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalEmployers' : bigint,
  'totalJobs' : bigint,
  'totalUsers' : bigint,
  'activeJobs' : bigint,
  'totalApplications' : bigint,
}
export interface Course {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export interface EmployerProfile {
  'description' : string,
  'companyName' : string,
  'location' : string,
  'industry' : string,
}
export interface JobApplication {
  'id' : bigint,
  'job' : JobListing,
  'status' : string,
  'workerId' : Principal,
  'worker' : WorkerProfile,
}
export interface JobListing {
  'id' : bigint,
  'title' : string,
  'salary' : string,
  'description' : string,
  'company' : string,
  'employerId' : Principal,
  'approved' : boolean,
  'category' : string,
  'location' : string,
}
export interface RecentActivity {
  'recentJobs' : Array<JobListing>,
  'recentApplications' : Array<JobApplication>,
}
export interface UserProfile {
  'profileType' : { 'employer' : null } |
    { 'worker' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkerProfile {
  'name' : string,
  'experience' : bigint,
  'skills' : Array<string>,
  'location' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveJob' : ActorMethod<[bigint], undefined>,
  'adminBlockUser' : ActorMethod<[Principal], undefined>,
  'adminDeleteEmployer' : ActorMethod<[Principal], undefined>,
  'adminDeleteJob' : ActorMethod<[bigint], undefined>,
  'adminDeleteWorker' : ActorMethod<[Principal], undefined>,
  'adminGetAllApplications' : ActorMethod<[], Array<JobApplication>>,
  'adminGetAllEmployerActivity' : ActorMethod<
    [],
    Array<[Principal, EmployerProfile, bigint, bigint, string]>
  >,
  'adminGetAllEmployerPlans' : ActorMethod<[], Array<[Principal, string]>>,
  'adminGetAllEmployers' : ActorMethod<[], Array<[Principal, EmployerProfile]>>,
  'adminGetAllWorkers' : ActorMethod<[], Array<[Principal, WorkerProfile]>>,
  'adminGetRecentActivity' : ActorMethod<[], RecentActivity>,
  'adminGetStats' : ActorMethod<[], AdminStats>,
  'adminSetEmployerPlan' : ActorMethod<[Principal, string], undefined>,
  'adminUnblockUser' : ActorMethod<[Principal], undefined>,
  'applyToJob' : ActorMethod<[bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCourse' : ActorMethod<[string, string], bigint>,
  'createJobListing' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'deleteCourse' : ActorMethod<[bigint], undefined>,
  'deleteJobListing' : ActorMethod<[bigint], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllJobs' : ActorMethod<[], Array<JobListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourse' : ActorMethod<[bigint], [] | [Course]>,
  'getEmployerProfile' : ActorMethod<[Principal], [] | [EmployerProfile]>,
  'getJob' : ActorMethod<[bigint], [] | [JobListing]>,
  'getJobApplications' : ActorMethod<[bigint], Array<JobApplication>>,
  'getMyApplications' : ActorMethod<[], Array<JobApplication>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerProfile' : ActorMethod<[Principal], [] | [WorkerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEmployerProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'saveWorkerProfile' : ActorMethod<
    [string, Array<string>, string, bigint],
    undefined
  >,
  'updateApplicationStatus' : ActorMethod<[bigint, string], undefined>,
  'updateCourse' : ActorMethod<[bigint, string, string], undefined>,
  'updateJobListing' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];