/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'salary' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'employerId' : IDL.Principal,
  'approved' : IDL.Bool,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const WorkerProfile = IDL.Record({
  'name' : IDL.Text,
  'experience' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const JobApplication = IDL.Record({
  'id' : IDL.Nat,
  'job' : JobListing,
  'status' : IDL.Text,
  'workerId' : IDL.Principal,
  'worker' : WorkerProfile,
});
export const EmployerProfile = IDL.Record({
  'description' : IDL.Text,
  'companyName' : IDL.Text,
  'location' : IDL.Text,
  'industry' : IDL.Text,
});
export const RecentActivity = IDL.Record({
  'recentJobs' : IDL.Vec(JobListing),
  'recentApplications' : IDL.Vec(JobApplication),
});
export const AdminStats = IDL.Record({
  'totalEmployers' : IDL.Nat,
  'totalJobs' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'activeJobs' : IDL.Nat,
  'totalApplications' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'profileType' : IDL.Variant({ 'employer' : IDL.Null, 'worker' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveJob' : IDL.Func([IDL.Nat], [], []),
  'adminBlockUser' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteEmployer' : IDL.Func([IDL.Principal], [], []),
  'adminDeleteJob' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteWorker' : IDL.Func([IDL.Principal], [], []),
  'adminGetAllApplications' : IDL.Func(
      [],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'adminGetAllEmployerActivity' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(IDL.Principal, EmployerProfile, IDL.Nat, IDL.Nat, IDL.Text)
        ),
      ],
      ['query'],
    ),
  'adminGetAllEmployerPlans' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      ['query'],
    ),
  'adminGetAllEmployers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, EmployerProfile))],
      ['query'],
    ),
  'adminGetAllWorkers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, WorkerProfile))],
      ['query'],
    ),
  'adminGetRecentActivity' : IDL.Func([], [RecentActivity], ['query']),
  'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
  'adminSetEmployerPlan' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'adminUnblockUser' : IDL.Func([IDL.Principal], [], []),
  'applyToJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCourse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCourse' : IDL.Func([IDL.Nat], [], []),
  'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
  'getEmployerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EmployerProfile)],
      ['query'],
    ),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobListing)], ['query']),
  'getJobApplications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmployerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'saveWorkerProfile' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateCourse' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateJobListing' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'salary' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'employerId' : IDL.Principal,
    'approved' : IDL.Bool,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const WorkerProfile = IDL.Record({
    'name' : IDL.Text,
    'experience' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const JobApplication = IDL.Record({
    'id' : IDL.Nat,
    'job' : JobListing,
    'status' : IDL.Text,
    'workerId' : IDL.Principal,
    'worker' : WorkerProfile,
  });
  const EmployerProfile = IDL.Record({
    'description' : IDL.Text,
    'companyName' : IDL.Text,
    'location' : IDL.Text,
    'industry' : IDL.Text,
  });
  const RecentActivity = IDL.Record({
    'recentJobs' : IDL.Vec(JobListing),
    'recentApplications' : IDL.Vec(JobApplication),
  });
  const AdminStats = IDL.Record({
    'totalEmployers' : IDL.Nat,
    'totalJobs' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'activeJobs' : IDL.Nat,
    'totalApplications' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'profileType' : IDL.Variant({ 'employer' : IDL.Null, 'worker' : IDL.Null }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveJob' : IDL.Func([IDL.Nat], [], []),
    'adminBlockUser' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteEmployer' : IDL.Func([IDL.Principal], [], []),
    'adminDeleteJob' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteWorker' : IDL.Func([IDL.Principal], [], []),
    'adminGetAllApplications' : IDL.Func(
        [],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'adminGetAllEmployerActivity' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              EmployerProfile,
              IDL.Nat,
              IDL.Nat,
              IDL.Text,
            )
          ),
        ],
        ['query'],
      ),
    'adminGetAllEmployerPlans' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        ['query'],
      ),
    'adminGetAllEmployers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, EmployerProfile))],
        ['query'],
      ),
    'adminGetAllWorkers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, WorkerProfile))],
        ['query'],
      ),
    'adminGetRecentActivity' : IDL.Func([], [RecentActivity], ['query']),
    'adminGetStats' : IDL.Func([], [AdminStats], ['query']),
    'adminSetEmployerPlan' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'adminUnblockUser' : IDL.Func([IDL.Principal], [], []),
    'applyToJob' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCourse' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCourse' : IDL.Func([IDL.Nat], [], []),
    'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllJobs' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourse' : IDL.Func([IDL.Nat], [IDL.Opt(Course)], ['query']),
    'getEmployerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(JobListing)], ['query']),
    'getJobApplications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getMyApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmployerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'saveWorkerProfile' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateCourse' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateJobListing' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };